# If set to false, the plugin will not register any listeners or send messages
enabled: true

# This contains all configurable messages used by the plugin
messages:
  # Messages used for all players unless overridden by group or player rules
  default:
    # Placeholders: <player>
    join:
      - "<green><player> joined the server"
      - "<green><player> is now online"

    # Placeholders: <player>
    first-join:
      - "<yellow>Welcome <player> to the server"
      - "<yellow><player> joined the server for the first time"

    # Placeholders: <player>
    quit:
      - "<red><player> left the server"
      - "<red><player> went offline"

    # Placeholders: <player>, <message>
    death:
      - "<red><message>"

    # Placeholders: <player>, <message>
    chat:
      - "<gray><player>: <white><message>"

    # Placeholders: <player>, <advancement>, <color>
    advancement:
      - "<color><player> has made the advancement <advancement>"

  # Overrides default messages for players in specific LuckPerms groups
  # Group messages have lower priority than player-specific messages
  group_based:
    # Messages for players in the 'admin' group
    admin:
      # Placeholders: <player>
      join:
        - "<red>Admin <player> has joined the server"
        - "<red>Admin <player> is now online"

  # Overrides all other messages for specific players
  # Player names must match exact Minecraft usernames
  player_specific:
    # Messages for the player 'Notch'
    Notch:
      # Placeholders: <player>
      join:
        - "<light_purple>Notch has joined the server"
        - "<light_purple>Notch is now online"

  # Message sent to the console when the plugin is enabled or disabled
  lifecycle:
    enable: "Enabled Letters v<version>"
    disable: "Disabled Letters v<version>"

  # Message sent to the console before the plugin disables itself due to a config option
  status:
    disabled: "Plugin is disabled in config."

  # Message sent to the console when the plugin checks for dependency plugins
  dependencies:
    placeholder_api:
      found: "PlaceholderAPI detected. Additional placeholders will work"
      not_found: "PlaceholderAPI not detected. Additional placeholders will not work"

    luckperms:
      found: "LuckPerms detected. Group-based messages will work"
      not_found: "LuckPerms not detected. Group-based messages will not work"

    vanish:
      found: "<plugin> detected. Vanish-related features will work"
      not_found: "SuperVanish or PremiumVanish not detected. Vanish-related features will not work"